// <auto-generated />
using System;
using B2A.DbTula.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace B2A.DbTula.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531165841_AddPhase2Tables")]
    partial class AddPhase2Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("B2A.DbTula.Api.Data.AllowedEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AllowedEmails");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.ComparisonProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IgnoreOwnership")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SourceDbId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetDbId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("SourceDbId");

                    b.HasIndex("TargetDbId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.ComparisonRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("InitiatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<Guid>("SourceDbId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SummaryJson")
                        .HasColumnType("text");

                    b.Property<string>("SyncScriptDestructive")
                        .HasColumnType("text");

                    b.Property<string>("SyncScriptRisky")
                        .HasColumnType("text");

                    b.Property<string>("SyncScriptSafe")
                        .HasColumnType("text");

                    b.Property<Guid>("TargetDbId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InitiatedById");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SourceDbId");

                    b.HasIndex("TargetDbId");

                    b.ToTable("ComparisonRuns");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.DbSyncStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AppliedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ComparisonRunId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Sql")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppliedById");

                    b.HasIndex("ComparisonRunId", "Category");

                    b.ToTable("SyncStatements", (string)null);
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.DriftMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComparisonRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("MatchCount")
                        .HasColumnType("integer");

                    b.Property<int>("MismatchCount")
                        .HasColumnType("integer");

                    b.Property<int>("MissingInSourceCount")
                        .HasColumnType("integer");

                    b.Property<int>("MissingInTargetCount")
                        .HasColumnType("integer");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RunDate");

                    b.HasIndex("ComparisonRunId", "ObjectType");

                    b.ToTable("DriftMetrics");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.RegisteredDatabase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionStringEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("DbType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsWriteAccount")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReadAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Databases");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.SyncApplyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AppliedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComparisonRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<string>("SqlExecuted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetDbId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppliedById");

                    b.HasIndex("ComparisonRunId");

                    b.HasIndex("TargetDbId");

                    b.ToTable("SyncApplyLogs");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.AllowedEmail", b =>
                {
                    b.HasOne("B2A.DbTula.Api.Data.AppUser", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedBy");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.ComparisonProfile", b =>
                {
                    b.HasOne("B2A.DbTula.Api.Data.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("B2A.DbTula.Api.Data.RegisteredDatabase", "SourceDb")
                        .WithMany()
                        .HasForeignKey("SourceDbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("B2A.DbTula.Api.Data.RegisteredDatabase", "TargetDb")
                        .WithMany()
                        .HasForeignKey("TargetDbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("SourceDb");

                    b.Navigation("TargetDb");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.ComparisonRun", b =>
                {
                    b.HasOne("B2A.DbTula.Api.Data.AppUser", "InitiatedBy")
                        .WithMany("Runs")
                        .HasForeignKey("InitiatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("B2A.DbTula.Api.Data.ComparisonProfile", "Profile")
                        .WithMany("Runs")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("B2A.DbTula.Api.Data.RegisteredDatabase", "SourceDb")
                        .WithMany()
                        .HasForeignKey("SourceDbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("B2A.DbTula.Api.Data.RegisteredDatabase", "TargetDb")
                        .WithMany()
                        .HasForeignKey("TargetDbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InitiatedBy");

                    b.Navigation("Profile");

                    b.Navigation("SourceDb");

                    b.Navigation("TargetDb");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.DbSyncStatement", b =>
                {
                    b.HasOne("B2A.DbTula.Api.Data.AppUser", "AppliedBy")
                        .WithMany()
                        .HasForeignKey("AppliedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("B2A.DbTula.Api.Data.ComparisonRun", "ComparisonRun")
                        .WithMany()
                        .HasForeignKey("ComparisonRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppliedBy");

                    b.Navigation("ComparisonRun");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.DriftMetric", b =>
                {
                    b.HasOne("B2A.DbTula.Api.Data.ComparisonRun", "ComparisonRun")
                        .WithMany()
                        .HasForeignKey("ComparisonRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComparisonRun");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.RegisteredDatabase", b =>
                {
                    b.HasOne("B2A.DbTula.Api.Data.AppUser", "CreatedBy")
                        .WithMany("Databases")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.SyncApplyLog", b =>
                {
                    b.HasOne("B2A.DbTula.Api.Data.AppUser", "AppliedBy")
                        .WithMany("ApplyLogs")
                        .HasForeignKey("AppliedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("B2A.DbTula.Api.Data.ComparisonRun", "ComparisonRun")
                        .WithMany("ApplyLogs")
                        .HasForeignKey("ComparisonRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("B2A.DbTula.Api.Data.RegisteredDatabase", "TargetDb")
                        .WithMany()
                        .HasForeignKey("TargetDbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppliedBy");

                    b.Navigation("ComparisonRun");

                    b.Navigation("TargetDb");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.AppUser", b =>
                {
                    b.Navigation("ApplyLogs");

                    b.Navigation("Databases");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.ComparisonProfile", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("B2A.DbTula.Api.Data.ComparisonRun", b =>
                {
                    b.Navigation("ApplyLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
