using B2A.DbTula.Cli;
using B2A.DbTula.Core.Enums;
using B2A.DbTula.Core.Models;
using B2A.DbTula.Core.Semantics;

namespace B2A.DbTula.Tests;

/// <summary>
/// Covers the identity / serial / sequence generation-strategy detector and the
/// semantic drift classifier. These run with no database — pure model logic.
/// </summary>
public class GenerationStrategyTests
{
    // ── builders ──────────────────────────────────────────────────────────────
    private static ColumnDefinition IdentityByDefault(string name = "id") =>
        new() { Name = name, DataType = "integer", IsNullable = false, IsIdentity = true, IdentityGeneration = "BY DEFAULT" };

    private static ColumnDefinition IdentityAlways(string name = "id") =>
        new() { Name = name, DataType = "integer", IsNullable = false, IsIdentity = true, IdentityGeneration = "ALWAYS" };

    private static ColumnDefinition Serial(string name = "id", string table = "company_sizers") =>
        new() { Name = name, DataType = "integer", IsNullable = false, DefaultValue = $"nextval('{table}_{name}_seq'::regclass)" };

    private static ColumnDefinition Plain(string name = "id") =>
        new() { Name = name, DataType = "integer", IsNullable = false };

    // ── strategy detection ────────────────────────────────────────────────────

    [Theory]
    [InlineData("BY DEFAULT", GenerationStrategy.IdentityByDefault)]
    [InlineData("ALWAYS", GenerationStrategy.IdentityAlways)]
    public void Detects_identity_kind(string generation, GenerationStrategy expected)
    {
        var col = new ColumnDefinition { Name = "id", DataType = "integer", IsIdentity = true, IdentityGeneration = generation };
        Assert.Equal(expected, col.GetGenerationStrategy());
    }

    [Fact]
    public void Detects_sequence_default_as_sequence_backed()
    {
        Assert.Equal(GenerationStrategy.SequenceDefault, Serial().GetGenerationStrategy());
        // ...and as Serial once ownership (pg_depend) is known
        Assert.Equal(GenerationStrategy.Serial, Serial().GetGenerationStrategy(sequenceIsOwned: true));
    }

    [Fact]
    public void Detects_plain_column_as_none()
    {
        Assert.Equal(GenerationStrategy.None, Plain().GetGenerationStrategy());
    }

    [Fact]
    public void Sequence_default_is_stripped_from_NonGenerationDefault()
    {
        Assert.Null(Serial().NonGenerationDefault);
        // a real literal default is preserved
        var lit = new ColumnDefinition { Name = "n", DataType = "integer", DefaultValue = "0" };
        Assert.Equal("0", lit.NonGenerationDefault);
    }

    // ── Case A: IDENTITY (QA) vs PLAIN (PROD) → Functional ────────────────────

    [Fact]
    public void CaseA_identity_vs_plain_is_functional_drift()
    {
        var d = GenerationStrategyAnalyzer.Analyze("company_sizers", IdentityByDefault(), Plain());

        Assert.Equal(DriftCategory.Functional, d.Category);
        Assert.Equal(LintSeverity.Error, d.Risk);
        Assert.True(d.MigrationRequired);
        Assert.Contains("ADD GENERATED BY DEFAULT AS IDENTITY", d.MigrationScript);
    }

    // ── Case B: IDENTITY (QA) vs DEFAULT nextval (PROD) → Metadata ────────────

    [Fact]
    public void CaseB_identity_vs_sequence_default_is_metadata_drift()
    {
        var d = GenerationStrategyAnalyzer.Analyze("company_sizers", IdentityByDefault(), Serial());

        Assert.Equal(DriftCategory.Metadata, d.Category);
        Assert.Equal(LintSeverity.Info, d.Risk);
        Assert.False(d.MigrationRequired);
        Assert.True(d.IsSuppressible);
        Assert.Null(d.MigrationScript);
    }

    // ── Case C: SERIAL (QA) vs IDENTITY (PROD) → Metadata, not required ───────

    [Fact]
    public void CaseC_serial_vs_identity_is_metadata_drift()
    {
        var d = GenerationStrategyAnalyzer.Analyze("company_sizers", Serial(), IdentityByDefault());

        Assert.Equal(DriftCategory.Metadata, d.Category);
        Assert.False(d.MigrationRequired);
    }

    // ── Case D: identical IDENTITY but sequence behind MAX(id) → Data Integrity

    [Fact]
    public void CaseD_sequence_behind_max_is_data_integrity_drift()
    {
        var sync = new SequenceSyncState
        {
            SequenceName = "company_sizers_id_seq",
            LastValue = 42,
            MaxColumnValue = 1007
        };

        var d = GenerationStrategyAnalyzer.Analyze("company_sizers", IdentityByDefault(), IdentityByDefault(), sync);

        Assert.Equal(DriftCategory.DataIntegrity, d.Category);
        Assert.Equal(LintSeverity.Error, d.Risk);
        Assert.True(d.MigrationRequired);
        Assert.Contains("setval('company_sizers_id_seq'", d.MigrationScript);
    }

    [Fact]
    public void Healthy_sequence_in_sync_is_not_flagged()
    {
        var sync = new SequenceSyncState { SequenceName = "s", LastValue = 1007, MaxColumnValue = 1007 };
        var d = GenerationStrategyAnalyzer.Analyze("t", IdentityByDefault(), IdentityByDefault(), sync);
        Assert.False(d.IsDrift);
    }

    // ── GENERATED ALWAYS vs BY DEFAULT → Functional (explicit-insert behaviour)

    [Fact]
    public void Identity_always_vs_by_default_is_functional_drift()
    {
        var d = GenerationStrategyAnalyzer.Analyze("t", IdentityAlways(), IdentityByDefault());

        Assert.Equal(DriftCategory.Functional, d.Category);
        Assert.True(d.MigrationRequired);
        Assert.Contains("SET GENERATED ALWAYS", d.MigrationScript);
    }

    // ── identical strategy → no drift ─────────────────────────────────────────

    [Fact]
    public void Identical_identity_is_not_drift()
    {
        var d = GenerationStrategyAnalyzer.Analyze("t", IdentityByDefault(), IdentityByDefault());
        Assert.False(d.IsDrift);
        Assert.Equal(DriftCategory.None, d.Category);
    }

    // ── end-to-end through the comparer ───────────────────────────────────────

    private static MockSchemaProvider Provider(string table, ColumnDefinition idCol) => new()
    {
        Tables = [table],
        TableDefs = { [table] = new TableDefinition { Name = table, Columns = [idCol] } }
    };

    [Fact]
    public async Task Comparer_CaseA_identity_vs_plain_reports_mismatch()
    {
        var qa = Provider("company_sizers", IdentityByDefault());
        var prod = Provider("company_sizers", Plain());

        var results = await new SchemaComparer().CompareAsync(qa, prod);

        var r = Assert.Single(results.Where(x => x.ObjectType == SchemaObjectType.Table));
        Assert.Equal(ComparisonStatus.Mismatch, r.Status);
        var sub = Assert.Single(r.SubResults.Where(s => s.Component == "Columns"));
        Assert.Equal(DriftCategory.Functional, sub.Category);
        Assert.True(sub.MigrationRequired);
    }

    [Fact]
    public async Task Comparer_CaseB_identity_vs_serial_is_not_a_false_positive()
    {
        var qa = Provider("company_sizers", IdentityByDefault());
        var prod = Provider("company_sizers", Serial());

        var results = await new SchemaComparer().CompareAsync(qa, prod);

        var r = Assert.Single(results.Where(x => x.ObjectType == SchemaObjectType.Table));
        // Equivalent generation strategies must NOT flip the table to Mismatch.
        Assert.Equal(ComparisonStatus.Match, r.Status);
        Assert.DoesNotContain(r.SubResults, s => s.Status == ComparisonStatus.Mismatch);
        // ...but the informational metadata note is still recorded.
        Assert.Contains(r.SubResults, s => s.Component == "Columns" && s.Category == DriftCategory.Metadata);
    }

    [Fact]
    public async Task Identity_shorthand_vs_expanded_default_options_is_not_drift()
    {
        // QA written as shorthand:  id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL
        // PROD written expanded:    ...AS IDENTITY (INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647
        //                                           START 1 CACHE 1 NO CYCLE) NOT NULL
        // Both are the SAME column to the catalog: identity_generation='BY DEFAULT',
        // column_default=NULL, data_type=int4. The expanded options are just the implicit
        // identity-sequence defaults, and that sequence is excluded from comparison.
        var qa = Provider("company_sizers", IdentityByDefault());
        var prod = Provider("company_sizers", IdentityByDefault());

        var results = await new SchemaComparer().CompareAsync(qa, prod);

        var r = Assert.Single(results.Where(x => x.ObjectType == SchemaObjectType.Table));
        Assert.Equal(ComparisonStatus.Match, r.Status);
        Assert.DoesNotContain(r.SubResults, s => s.Status == ComparisonStatus.Mismatch);
    }

    [Fact]
    public void Identity_sequence_with_explicit_int4_defaults_is_recognized_as_default()
    {
        // The exact options the user listed ARE the int4 identity-sequence defaults.
        var int4Defaults = new DbSequenceDefinition
        {
            Name = "company_sizers_id_seq", DataType = "integer",
            IncrementBy = 1, MinValue = 1, MaxValue = 2147483647, StartValue = 1, CacheSize = 1, Cycle = false
        };
        Assert.True(int4Defaults.HasIntegerTypeDefaults());

        // bigint defaults differ only in MAXVALUE and are still "default" for their type.
        var int8Defaults = new DbSequenceDefinition
        {
            Name = "s", DataType = "bigint",
            IncrementBy = 1, MinValue = 1, MaxValue = 9223372036854775807, StartValue = 1, CacheSize = 1, Cycle = false
        };
        Assert.True(int8Defaults.HasIntegerTypeDefaults());

        // A genuinely non-default option (CACHE 20) is NOT a default — real drift, must stay visible.
        var tuned = new DbSequenceDefinition
        {
            Name = "s", DataType = "integer",
            IncrementBy = 1, MinValue = 1, MaxValue = 2147483647, StartValue = 1, CacheSize = 20, Cycle = false
        };
        Assert.False(tuned.HasIntegerTypeDefaults());

        // Crucially, an int4-bounded and an int8-bounded sequence are NOT equal — type drift
        // must never be normalized away.
        Assert.False(int4Defaults.StructuralEquals(int8Defaults));
    }

    [Fact]
    public void EqualsIgnoringGeneration_treats_identity_and_serial_as_equal_shape()
    {
        // identity (no default) vs serial (nextval default) — same column shape otherwise
        Assert.True(IdentityByDefault().EqualsIgnoringGeneration(Serial()));
        // a genuine type difference is still caught
        var bigint = new ColumnDefinition { Name = "id", DataType = "bigint", IsNullable = false, IsIdentity = true, IdentityGeneration = "BY DEFAULT" };
        Assert.False(IdentityByDefault().EqualsIgnoringGeneration(bigint));
    }
}
