name: DB Schema Comparison

on:
  schedule:
    - cron: '30 18 * * *'   # Every day at midnight IST (18:30 UTC)
  workflow_dispatch:

jobs:
  compare-schemas:
    runs-on: ubuntu-latest

    env:
      # Source (QA)
      QA_DB_HOST: ${{ secrets.QA_DB_HOST }}
      QA_DB_PORT: ${{ secrets.QA_DB_PORT }}
      QA_DB_USER: ${{ secrets.QA_DB_USER }}
      QA_DB_PASSWORD: ${{ secrets.QA_DB_PASSWORD }}

      # Target (PROD)
      PROD_DB_HOST: ${{ secrets.PROD_DB_HOST }}
      PROD_DB_PORT: ${{ secrets.PROD_DB_PORT }}
      PROD_DB_USER: ${{ secrets.PROD_DB_USER }}
      PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}

      # Target (TEST)
      TEST_DB_HOST: ${{ secrets.TEST_DB_HOST }}
      TEST_DB_PORT: ${{ secrets.TEST_DB_PORT }}
      TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
      TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore src/B2A.DbTula.Cli/B2A.DbTula.Cli.csproj

      - name: Build CLI Tool
        run: dotnet build src/B2A.DbTula.Cli/B2A.DbTula.Cli.csproj --configuration Release

      - name: Run Schema Comparison for QA vs PROD
        run: |
          services=("common" "community" "inventory" "payroll" "purchase" "sales")
          mkdir -p gh-pages/qa-vs-prod

          for service in "${services[@]}"; do
            echo "Comparing QA → PROD for $service..."
            SOURCE_CONN="Server=${QA_DB_HOST};Port=${QA_DB_PORT};Database=qa-dhanman-${service};User Id=${QA_DB_USER};Password=${QA_DB_PASSWORD};"
            TARGET_CONN="Server=${PROD_DB_HOST};Port=${PROD_DB_PORT};Database=prod-dhanman-${service};User Id=${PROD_DB_USER};Password=${PROD_DB_PASSWORD};"

            dotnet run --project src/B2A.DbTula.Cli/B2A.DbTula.Cli.csproj --configuration Release -- \
              --source "$SOURCE_CONN" \
              --target "$TARGET_CONN" \
              --title "${service} Schema Comparison Report (QA vs PROD)" \
              --out "gh-pages/qa-vs-prod/${service}.html"
          done

      - name: Run Schema Comparison for QA vs TEST
        run: |
          services=("common" "community" "inventory" "payroll" "purchase" "sales")
          mkdir -p gh-pages/qa-vs-test

          for service in "${services[@]}"; do
            echo "Comparing QA → TEST for $service..."
            SOURCE_CONN="Server=${QA_DB_HOST};Port=${QA_DB_PORT};Database=qa-dhanman-${service};User Id=${QA_DB_USER};Password=${QA_DB_PASSWORD};"
            TARGET_CONN="Server=${TEST_DB_HOST};Port=${TEST_DB_PORT};Database=test-dhanman-${service};User Id=${TEST_DB_USER};Password=${TEST_DB_PASSWORD};"

            dotnet run --project src/B2A.DbTula.Cli/B2A.DbTula.Cli.csproj --configuration Release -- \
              --source "$SOURCE_CONN" \
              --target "$TARGET_CONN" \
              --title "${service} Schema Comparison Report (QA vs TEST)" \
              --out "gh-pages/qa-vs-test/${service}.html"
          done

      - name: List generated reports (debug)
        run: ls -R gh-pages

      - name: Deploy Schema Reports to OVH (QA vs PROD and QA vs TEST)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          password: ${{ secrets.DO_PASSWORD }}
          port: 22
          source: |
            gh-pages/qa-vs-prod/
            gh-pages/qa-vs-test/
          target: "/var/www/dbtula-site"
          strip_components: 1
          timeout: 30s
          command_timeout: 10m
          debug: true
