name: DB Schema Comparison

on:
  workflow_dispatch: # Trigger manually for now

jobs:
  compare-schemas:
    runs-on: ubuntu-latest

    env:
      # Source (QA)
      QA_DB_HOST: ${{ secrets.QA_DB_HOST }}
      QA_DB_PORT: ${{ secrets.QA_DB_PORT }}
      QA_DB_USER: ${{ secrets.QA_DB_USER }}
      QA_DB_PASSWORD: ${{ secrets.QA_DB_PASSWORD }}

      # Target (PROD)
      PROD_DB_HOST: ${{ secrets.PROD_DB_HOST }}
      PROD_DB_PORT: ${{ secrets.PROD_DB_PORT }}
      PROD_DB_USER: ${{ secrets.PROD_DB_USER }}
      PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore src/B2A.DbTula.Cli/B2A.DbTula.Cli.csproj

      - name: Build CLI Tool
        run: dotnet build src/B2A.DbTula.Cli/B2A.DbTula.Cli.csproj --configuration Release

      - name: Run Schema Comparison for All DBs
        run: |
          services=("common" "community" "inventory" "payroll" "purchase" "sales")
          # services=("inventory")
          mkdir -p gh-pages

          for service in "${services[@]}"; do
            echo "Comparing $service..."

            SOURCE_CONN="Server=${QA_DB_HOST};Port=${QA_DB_PORT};Database=qa-dhanman-${service};User Id=${QA_DB_USER};Password=${QA_DB_PASSWORD};"
            TARGET_CONN="Server=${PROD_DB_HOST};Port=${PROD_DB_PORT};Database=prod-dhanman-${service};User Id=${PROD_DB_USER};Password=${PROD_DB_PASSWORD};"

            dotnet run --project src/B2A.DbTula.Cli/B2A.DbTula.Cli.csproj --configuration Release -- \
              --source "$SOURCE_CONN" \
              --target "$TARGET_CONN" \
              --title "${service} Schema Comparison Report" \
              --test \
              --limit 5 \
              --out "gh-pages/${service}.html"
          done

      - name: Deploy Schema Reports to OVH (without index.html)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          password: ${{ secrets.DO_PASSWORD }}
          port: 22
          source: "gh-pages/*.html"
          target: "/var/www/dbtula-site"
          strip_components: 1
          timeout: 30s
          command_timeout: 10m
          debug: true
