name: DB Schema Comparison

on:
  workflow_dispatch: # Trigger manually for now

jobs:
  compare-schemas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore src/b2a.db-tula/b2a.db-tula.cli/b2a.db-tula.cli.csproj

      - name: Build CLI Tool
        run: dotnet build src/b2a.db-tula/b2a.db-tula.cli/b2a.db-tula.cli.csproj --configuration Release

      - name: Run Schema Comparison
        run: |
          dotnet run --project src/b2a.db-tula/b2a.db-tula.cli/b2a.db-tula.cli.csproj --configuration Release -- \
            --source "${{ secrets.SOURCE_COMMON_DB_CONNECTION }}" \
            --target "${{ secrets.TARGET_COMMON_DB_CONNECTION }}"

      - name: Prepare GitHub Pages folder
        run: |
          mkdir gh-pages
          cp schema-comparison-report.html gh-pages/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages

